#!/bin/sh
# Build the complete Pilot with the nine assembly optimizations. Run on the Pi.
set -eu
cd "$(dirname "$0")/.."

compiler=${CC:-gcc}
compiler_target=$("$compiler" -dumpmachine)
case "$compiler_target" in
    aarch64*linux*) ;;
    *) printf '%s\n' 'Use a compiler targeting 64-bit ARM Linux (GCC on the Pi).' >&2; exit 1 ;;
esac

mkdir -p build/pi

# The standalone IO_main.s is a separate executable's entry point. Carry its
# fixed 100 ms delay into a generated copy of Pilot's main, preserving the C
# baseline and all hand-edited assembly files.
python3 - <<'PY'
from pathlib import Path

source = Path('Development/CritterProduct/Pilot/main.c').read_text()
interval = '    const double sample_interval_s = 0.1;\n'
old_delay = '''            struct timespec sleep_ts;

            sleep_ts.tv_sec = (time_t)sample_interval_s;
            sleep_ts.tv_nsec =
                (long)((sample_interval_s - (double)sleep_ts.tv_sec) * 1000000000.0);'''
new_delay = '''            struct timespec sleep_ts = {.tv_sec = 0, .tv_nsec = 100000000L};'''
if source.count(interval) != 1 or source.count(old_delay) != 1:
    raise SystemExit('Pilot main changed: review the fixed-delay replacement before building.')
source = source.replace(interval, '').replace(old_delay, new_delay)
Path('build/pi/Pilot_main_asm.c').write_text(
    '/* Generated by PowerAssessment/build_pilot_asm.sh; do not edit. */\n' + source)
PY

"$compiler" -std=c11 -O0 -Wall -Wextra -I Development/CritterProduct/Pilot \
    -S -fverbose-asm build/pi/Pilot_main_asm.c -o build/pi/Pilot_main_asm.s

"$compiler" build/pi/Pilot_main_asm.s \
    PowerAssessment/asm/edited/critter_io.s \
    PowerAssessment/asm/edited/sense_hat_environment.s \
    PowerAssessment/asm/edited/critter_memory.s \
    PowerAssessment/asm/edited/critter_computation.s \
    -lm -o build/pi/Pilot_asm

printf '%s\n' 'Built build/pi/Pilot_asm (full program; all nine optimizations).'
